add web-ext config and ignore files from build, fixes #135
mozilla-ion/ion-core-addon pull request #142
Opened 2020-11-12 00:31 UTC by rhelmer

I don't see a great way to include vs. exclude files, unfortunately :( this does the job for right now.

2020-11-12 01:40 UTC, pdehaan commented
Current list of files in the built add-on:

```sh
npm run build-addon
npx web-ext build
zipinfo -1 web-ext-artifacts/ion_core-2.0.zip | sort | grep -Ev "/$"

core-addon/DataCollection.js
core-addon/FirefoxPrivilegedApi.js
core-addon/FirefoxPrivilegedApi.schema.json
core-addon/IonCore.js
core-addon/Storage.js
core-addon/background.js
core-addon/content-script.js
images/ion.svg
manifest.json
public/addon-build/background.js
public/addon-build/content-script.js
public/build/bundle.css
public/build/bundle.css.map
public/build/bundle.js
public/build/bundle.js.map
public/common.css
public/favicon.png
public/favicon.svg
public/fonts/Inter-Bold.woff
public/fonts/Inter-Bold.woff2
public/fonts/Inter-BoldItalic.woff
public/fonts/Inter-BoldItalic.woff2
public/fonts/Inter-Italic.woff
public/fonts/Inter-Italic.woff2
public/fonts/Inter-Regular.woff
public/fonts/Inter-Regular.woff2
public/fonts/Metropolis-Bold.woff
public/fonts/Metropolis-Bold.woff2
public/fonts/Metropolis-Medium.woff
public/fonts/Metropolis-Medium.woff2
public/fonts/ZillaSlab-Bold.woff
public/fonts/ZillaSlab-Bold.woff2
public/fonts/ZillaSlab-BoldItalic.woff
public/fonts/ZillaSlab-BoldItalic.woff2
public/fonts/ZillaSlab-Regular.woff
public/fonts/ZillaSlab-Regular.woff2
public/fonts/ZillaSlab-RegularItalic.woff
public/fonts/ZillaSlab-RegularItalic.woff2
public/global.css
public/index.html
public/locally-available-studies.json
public/rally.css
public/tokens.css
```

Re: > _"I don't see a great way to include vs. exclude files, unfortunately..."_

Not sure if moving the add-on files into an addon specific subdirectory would help. Possibly like this:

```sh
addon/
├── core-addon/...
├── images/ion.svg
├── manifest.json
└── public/...
```

Then, when we run <kbd>web-ext build -s addon</kbd> (or better yet, edit the web-ext-config.js config to specify the `sourceDir: "addon"` so it works with all commands), it should only include files in that specific directory and we can probably lose all the files listed in the `ignoreFiles[]` array in the web-ext config.

2020-11-12 01:48 UTC, pdehaan commented on web-ext-config.js
> +module.exports = {
Needs MPL header. ❤️ 

```
/home/circleci/project/web-ext-config.js
  1:1  error  Missing notice header  notice/notice

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

2020-11-12 09:59 UTC, Dexterp37 requested changes

2020-11-12 09:59 UTC, Dexterp37 commented on web-ext-config.js
> +  ignoreFiles: [
I think we should also add `core-addon/**/*` and `public/**/*.map`: the manifest includes the bundled code which lives in `public/addon-build`, the original code is not required in the packaged addon.

2020-11-18 16:50 UTC, rhelmer commented
> Re: > _"I don't see a great way to include vs. exclude files, unfortunately..."_
> 
> Not sure if moving the add-on files into an addon specific subdirectory would help. Possibly like this:
> 
> ```shell
> addon/
> ├── core-addon/...
> ├── images/ion.svg
> ├── manifest.json
> └── public/...
> ```
> 
> Then, when we run web-ext build -s addon (or better yet, edit the web-ext-config.js config to specify the `sourceDir: "addon"` so it works with all commands), it should only include files in that specific directory and we can probably lose all the files listed in the `ignoreFiles[]` array in the web-ext config.

@Dexterp37 any thoughts on @pdehaan's suggestion above? I'd rather do an "include" vs. "exclude" strategy, this would get us closer to that.

2020-11-18 17:18 UTC, Dexterp37 commented
> @Dexterp37 any thoughts on @pdehaan's suggestion above? I'd rather do an "include" vs. "exclude" strategy, this would get us closer to that.

I love the idea of rationalizing this repo a bit more! +1 on that (include strategy).

2020-12-01 11:37 UTC, Dexterp37 approved these changes

2020-12-01 17:05 UTC, rhelmer commented
> 
> 
> > @Dexterp37 any thoughts on @pdehaan's suggestion above? I'd rather do an "include" vs. "exclude" strategy, this would get us closer to that.
> 
> I love the idea of rationalizing this repo a bit more! +1 on that (include strategy).

Filed issue #209 so we don't lose track of this, I think the PR as it stands is very simple and is better than what we have now so merging :)

2020-12-01 17:05 UTC, merged

2020-12-01 17:37 UTC, pdehaan commented
Minor Q (which I can file separately upon request), but I noticed if I build the add-on locally using `npx web-ext build`, and then inspect the bundled files, I see some odd stuff (highlighted in red below) in the "support/" directory:

```diff
zipinfo -1 ./web-ext-artifacts/ion_core-2.0.zip | sort | grep -Ev "/$"

images/ion.svg
manifest.json
public/addon-build/background.js
public/addon-build/content-script.js
public/build/bundle.css
public/build/bundle.js
public/build/protocol-extra.css
public/build/protocol.css
public/common.css
public/default-study-icon.png
public/favicon.png
public/favicon.svg
public/fonts/Inter-Bold.woff
public/fonts/Inter-Bold.woff2
public/fonts/Inter-BoldItalic.woff
public/fonts/Inter-BoldItalic.woff2
public/fonts/Inter-Italic.woff
public/fonts/Inter-Italic.woff2
public/fonts/Inter-Regular.woff
public/fonts/Inter-Regular.woff2
public/fonts/Metropolis-Bold.woff
public/fonts/Metropolis-Bold.woff2
public/fonts/Metropolis-Medium.woff
public/fonts/Metropolis-Medium.woff2
public/fonts/ZillaSlab-Bold.woff
public/fonts/ZillaSlab-Bold.woff2
public/fonts/ZillaSlab-BoldItalic.woff
public/fonts/ZillaSlab-BoldItalic.woff2
public/fonts/ZillaSlab-Regular.woff
public/fonts/ZillaSlab-Regular.woff2
public/fonts/ZillaSlab-RegularItalic.woff
public/fonts/ZillaSlab-RegularItalic.woff2
public/global.css
public/index.html
public/locally-available-studies.json
public/rally.css
public/texture.png
public/tokens.css
-support/README.md          <----- THIS
-support/package-lock.json  <----- THIS
-support/package.json       <----- THIS
support/rally.js
```

---

TL:DR: Do we need to include the following files in the support/ directory in the bundled add-on:
- support/README.md
- support/package-lock.json
- support/package.json

They're only about 850B unzipped, so the file size isn't a concern.